services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "85:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
      - db
    networks:
    - app_network
  db:
    image: mysql:8.0.0
    volumes:
    - /var/lib/mysql
    container_name: mysql8
    ports:
    - "3367:3366"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: full_poo
    networks:
    - app_network
  php:
    build: .
    container_name: php84
    volumes:
    - ./:/var/www/html
    networks:
    - app_network
networks:
  app_network:
    driver: bridge
